### PR TITLE
Hide page navigation, Site Configuration Settings Mapper, TYPO3 v12 compat...

### LINKED ISSUE #8: Support for TYPO3 v12 (silently dropped?)
Since the commit 108429f1871c6ce1a9bdd037891ad61dd4bd357c support for TYPO3 v12 has been dropped.
Is this by intention?

I'm considering using easyconf for our multisite system, but we are intentionally always one TYPO3 release behind the latest release. Which is currently v12.

The problem is that we need the fix for #6 - but this has been merged after you dropped v12 compatibility.

### PR DESCRIPTION
**Pull request by stigfaerch**
fixes #8 #13 #14
Also fixes number 1 and 4 of #12 

Sorry for such a big pull-request. Hope it's ok.

### CODE REVIEW

**Comment by buepro** [comment]
Thank you very much for this! After merging I have seen that phpstan fails. Do you have the possibility to look into it?

**Comment by stigfaerch** [comment]
@buepro 
Thanks for merging.
Unfortunately I have never been using phpstan before.
I tried to run `vendor/bin/phpstan analyse packages/typo3-easyconf/` from my local ddev installation. It found some errors but not the same as found from the automated checks.
The errors reported by the automated checks doesn't show the specific lines where something is found.
I haven't actually tested with TYPO3 v13, so I will install a local TYPO3 and try to see if things works as expected.

**Comment by stigfaerch** [comment]
Just made a pull request to fix TYPO3 v13 compatibility.
https://github.com/buepro/typo3-easyconf/pull/21
Maybe it could be an idea to have a dev-branch ?

**Comment by buepro** [comment]
Would it be fine for you to be a collaborator for that contribution gets easier for you?

**Comment by stigfaerch** [comment]
@buepro
Commenting just to let you know that I haven't abandoned the extension, and I am still working on this...

**Pull request merged**
